# Generated by Django 2.0.6 on 2018-06-22 19:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180622_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
